sudo: required
services:
  - docker

before_install:
  - docker build -t migot01/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run migot01/react-test npm test -- --coverage

after_success:
  - docker build -t migot01/multi-client ./client 
  - docker build -t migot01/multi-nginx ./nginx
  - docker build -t migot01/multi-server ./server
  - docker build -t migot01/multi-worker ./worker
#log in to the docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
# take the images ands push them to docker hub
  - docker push migot01/multi-client
  - docker push migot01/multi-nginx
  - docker push migot01/multi-server
  - docker push migot01/multi-worker
